---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }} and Gradle
        uses: ome/action-gradle@v3.2
        with:
          java-version: ${{ matrix.java }}
      - name: Run commands
        run: gradle ${{ env.gradle_commands }}

